spring.application.name=equipment-rental-api

server.port=8080
app.frontend-url=http://localhost:3000
app.seed.enabled=true

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orclpdb
spring.datasource.username=C##ROHAN
spring.datasource.password=CHANGE_ME
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
